<a href="https://colab.research.google.com/github/cjflanagan/example_repo_office_hours/blob/main/office_hours_github_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
example_data_from_github = pd.read_csv('https://raw.githubusercontent.com/cjflanagan/example_repo_office_hours/main/lending_club_data_example.csv')

In [3]:
example_data_from_github.head()

         id  member_id  ...  settlement_percentage  settlement_term
0  96409250        NaN  ...                    NaN              NaN
1  96191765        NaN  ...                    NaN              NaN
2  96419283        NaN  ...                    NaN              NaN
3  96379251        NaN  ...                    NaN              NaN
4  96249331        NaN  ...                    NaN              NaN

[5 rows x 150 columns]